# Generated by Django 3.1.4 on 2021-07-05 19:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('gold_weight', models.FloatField()),
                ('diamond_weight', models.FloatField()),
                ('category', models.CharField(max_length=64)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None)),
                ('user_id', models.IntegerField()),
                ('date_submitted', models.DateField()),
                ('diamond_quality', models.CharField(max_length=64)),
                ('gold_purity', models.CharField(max_length=64)),
                ('gold_weight', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('role_in_organisation', models.CharField(max_length=64)),
                ('website', models.CharField(max_length=64)),
                ('access', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
