# Generated by Django 3.1.4 on 2021-07-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='skus',
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.wishlist')),
            ],
        ),
    ]
