# Generated by Django 3.1.4 on 2021-07-13 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_auto_20210708_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
