# Generated by Django 3.1.4 on 2021-07-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210713_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='diamond_quality',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='gold_purity',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='gold_weight',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
