# Generated by Django 3.1.4 on 2021-07-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210714_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date_submitted',
            field=models.DateField(null=True),
        ),
    ]
