# Generated by Django 3.1.4 on 2021-07-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_wishlistitem_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='gold_weight',
            new_name='gold_color',
        ),
    ]
